server.port=8080

# Engine: JSOUP | SELENIUM | API
app.scraper.engine=SELENIUM

# Sandbox URL?lerini kendine göre güncelle:
app.target.baseUrl=https://sandbox.oxylabs.io/products   # ürün liste sayfas? (örnek)
app.demoApiUrl=https://sandbox.oxylabs.io/api/products   # demo json api (örnek)

# Scraping genel ayarlar
app.maxPages=3
app.userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
app.timeoutMs=15000
app.requestDelayMs=500

# CSS seçiciler (JSoup + Selenium için ortak)
app.selectors.product=.product-card
app.selectors.title=.product-title
app.selectors.price=.product-price
app.selectors.category=.product-category
app.selectors.link=.product-title a
app.selectors.image=img.product-image
app.selectors.next=.pagination .next:not(.disabled) a

# Cache süresi (dakika). 0 ? her istekte scrape et.
app.cache.ttlMinutes=10
